spring.application.name=api-gateway
server.port=8090

# Keycloak
keycloak.auth.jwk-set-uri=http://localhost:8091/realms/ticketing-security-realm/protocol/openid-connect/certs
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8091/realms/ticketing-security-realm

# Actuator
management.health.circuitbreakers.enabled=true
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# Resilience4j - Default Config
resilience4j.circuitbreaker.configs.default.registerHealthIndicator=true
resilience4j.circuitbreaker.configs.default.slidingWindowType=COUNT_BASED
resilience4j.circuitbreaker.configs.default.slidingWindowSize=8
resilience4j.circuitbreaker.configs.default.failureRateThreshold=50
resilience4j.circuitbreaker.configs.default.minimumNumberOfCalls=4
resilience4j.circuitbreaker.configs.default.waitDurationInOpenState=5s
resilience4j.circuitbreaker.configs.default.permittedNumberOfCallsInHalfOpenState=2
resilience4j.circuitbreaker.configs.default.automaticTransitionFromOpenToHalfOpenEnabled=true

# Resilience4j - Instances (servis isimlerini kendi servislerinle de?i?tir)
resilience4j.circuitbreaker.instances.ticket-service.baseConfig=default
resilience4j.circuitbreaker.instances.user-service.baseConfig=default

# TimeLimiter
resilience4j.timelimiter.configs.default.timeoutDuration=3s
resilience4j.timelimiter.instances.ticket-service.baseConfig=default
resilience4j.timelimiter.instances.user-service.baseConfig=default

# Retry
resilience4j.retry.configs.default.maxAttempts=3
resilience4j.retry.configs.default.waitDuration=2s
resilience4j.retry.instances.ticket-service.baseConfig=default
resilience4j.retry.instances.user-service.baseConfig=default